import { AIBountiesService, PendingBounty } from '../services/aiBountiesService';

// Category mapping
const categoryMap: { [key: number]: string } = {
  1: 'Nourish',
  2: 'Rest',
  3: 'Active Life',
  4: 'Connect',
  5: 'Mindset',
  6: 'Explore'
};

export class AIBountyGenerator {
  // Call the AI generation edge function
  private static async callAIGenerationAPI(bucketId: number, type: 'daily' | 'weekly' | 'yearly'): Promise<string[]> {
    try {
      console.log(`Calling AI generation API for bucket_id=${bucketId}, type=${type}`);
      
      const response = await fetch('https://nwfhqrmdjmjopbxulyhu.supabase.co/functions/v1/bountygen', {
        method: 'POST',
        headers: {
          'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53Zmhxcm1kam1qb3BieHVseWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNjc5MDMsImV4cCI6MjA2MTg0MzkwM30.NvbyIKp7BxALfO0SBpdFcbCXXhPcOJ_4YJY8HPyVlzs',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          bucket_id: 0,
          type: type
        })
      });

      console.log(`API Response status: ${response.status}`);
      
      if (!response.ok) {
        const errorText = await response.text();
        console.error(`API Error Response: ${errorText}`);
        throw new Error(`HTTP error! status: ${response.status}, message: ${errorText}`);
      }

      const data = await response.json();
      console.log('API Response data:', data);
      
      // Check if the response contains bounties
      if (data && Array.isArray(data) && data.length > 0 && data[0].bounties) {
        console.log(`Generated ${data[0].bounties.length} bounties for bucket_id=${bucketId}`);
        return data[0].bounties;
      } else if (data && data.error) {
        console.warn(`API returned error: ${data.error}`);
        throw new Error(`AI Generation failed: ${data.error}`);
      } else {
        console.warn(`No bounties generated for bucket_id=${bucketId} and type=${type}. Response:`, data);
        throw new Error(`No bounties generated for bucket_id=${bucketId} and type=${type}`);
      }
    } catch (error) {
      console.error(`Error calling AI generation API for bucket_id=${bucketId}, type=${type}:`, error);
      throw error;
    }
  }

  // Step A: AI Generation Function (runs independently)
  static async generateAndInsertBounties(
    categoryId?: number, 
    bountyType: 'daily' | 'weekly' | 'yearly' = 'daily',
    count: number = 3
  ): Promise<void> {
    try {
      console.log(`Generating ${count} ${bountyType} bounties for category ${categoryId || 'all'}`);
      
      const pendingBounties: PendingBounty[] = [];
      
      if (categoryId) {
        // Generate bounties for specific category
        const aiBounties = await this.callAIGenerationAPI(categoryId, bountyType);
        const selectedBounties = aiBounties.slice(0, count);
        
        selectedBounties.forEach(bounty => {
          pendingBounties.push({
            bucket_id: categoryId,
            category: categoryMap[categoryId],
            bounty: bounty,
            type: bountyType
          });
        });
      } else {
        // Generate bounties for all categories
        for (const catId of Object.keys(categoryMap)) {
          const categoryIdNum = parseInt(catId);
          const aiBounties = await this.callAIGenerationAPI(categoryIdNum, bountyType);
          const selectedBounties = aiBounties.slice(0, Math.ceil(count / 6));
          
          selectedBounties.forEach(bounty => {
            pendingBounties.push({
              bucket_id: categoryIdNum,
              category: categoryMap[categoryIdNum],
              bounty: bounty,
              type: bountyType
            });
          });
        }
      }
      
      // Step B: Insert into bounty_selection_history (status: pending)
      if (pendingBounties.length > 0) {
        await AIBountiesService.insertPendingBounties(pendingBounties);
        console.log(`Successfully inserted ${pendingBounties.length} pending bounties`);
      } else {
        console.warn('No bounties were generated by the AI service');
      }
      
    } catch (error) {
      console.error('Error generating and inserting bounties:', error);
      throw error;
    }
  }
  
  // Generate bounties for all categories
  static async generateAllCategoriesBounties(
    bountyType: 'daily' | 'weekly' | 'yearly' = 'daily',
    countPerCategory: number = 2
  ): Promise<void> {
    try {
      const pendingBounties: PendingBounty[] = [];
      const failedCategories: string[] = [];
      
      for (const catId of Object.keys(categoryMap)) {
        const categoryId = parseInt(catId);
        const categoryName = categoryMap[categoryId];
        
        try {
          console.log(`Generating bounties for category: ${categoryName} (ID: ${categoryId})`);
          const aiBounties = await this.callAIGenerationAPI(categoryId, bountyType);
          const selectedBounties = aiBounties.slice(0, countPerCategory);
          
          selectedBounties.forEach(bounty => {
            pendingBounties.push({
              bucket_id: categoryId,
              category: categoryName,
              bounty: bounty,
              type: bountyType
            });
          });
          
          console.log(`Successfully generated ${selectedBounties.length} bounties for ${categoryName}`);
        } catch (categoryError) {
          console.error(`Failed to generate bounties for category ${categoryName}:`, categoryError);
          failedCategories.push(categoryName);
        }
      }
      
      if (pendingBounties.length > 0) {
        await AIBountiesService.insertPendingBounties(pendingBounties);
        console.log(`Successfully inserted ${pendingBounties.length} pending bounties for all categories`);
        
        if (failedCategories.length > 0) {
          console.warn(`Failed to generate bounties for categories: ${failedCategories.join(', ')}`);
        }
      } else {
        throw new Error('No bounties were generated by the AI service for any category');
      }
      
    } catch (error) {
      console.error('Error generating all categories bounties:', error);
      throw error;
    }
  }
  
  // Generate bounties for specific category
  static async generateCategoryBounties(
    categoryId: number,
    bountyType: 'daily' | 'weekly' | 'yearly' = 'daily',
    count: number = 3
  ): Promise<void> {
    try {
      if (!categoryMap[categoryId]) {
        throw new Error(`Invalid category ID: ${categoryId}`);
      }
      
      const categoryName = categoryMap[categoryId];
      console.log(`Generating ${count} ${bountyType} bounties for category: ${categoryName} (ID: ${categoryId})`);
      
      const aiBounties = await this.callAIGenerationAPI(categoryId, bountyType);
      const selectedBounties = aiBounties.slice(0, count);
      
      if (selectedBounties.length === 0) {
        throw new Error(`No bounties were generated by the AI service for category ${categoryName}`);
      }
      
      const pendingBounties: PendingBounty[] = selectedBounties.map(bounty => ({
        bucket_id: categoryId,
        category: categoryName,
        bounty: bounty,
        type: bountyType
      }));
      
      await AIBountiesService.insertPendingBounties(pendingBounties);
      console.log(`Successfully inserted ${pendingBounties.length} pending bounties for category ${categoryName}`);
      
    } catch (error) {
      console.error(`Error generating category bounties for category ID ${categoryId}:`, error);
      throw error;
    }
  }
  
  // Get available categories
  static getAvailableCategories(): { id: number; name: string }[] {
    return Object.keys(categoryMap).map(id => ({
      id: parseInt(id),
      name: categoryMap[parseInt(id)]
    }));
  }
  
  // Get category name by ID
  static getCategoryName(categoryId: number): string {
    return categoryMap[categoryId] || 'Unknown';
  }
} 